"""baseline_schema

Revision ID: b386f0ba5efd
Revises: 
Create Date: 2026-08-07 14:22:08.267298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b386f0ba5efd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Enum('PF', 'PJ', name='clienttype'), nullable=False),
    sa.Column('email', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('saldo_credito', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=False)

    op.create_table('configuracoes_licenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('hwid', sa.String(length=255), nullable=False),
    sa.Column('licenca_id', sa.String(length=36), nullable=False),
    sa.Column('chave_ativacao', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('limite', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('ultima_sinc', sa.DateTime(), nullable=False),
    sa.Column('grace_period', sa.Integer(), nullable=False),
    sa.Column('proxima_validacao', sa.DateTime(), nullable=False),
    sa.Column('bloqueada', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licenca_id')
    )
    with op.batch_alter_table('configuracoes_licenca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_licenca_hwid'), ['hwid'], unique=True)
        batch_op.create_index(batch_op.f('ix_configuracoes_licenca_id'), ['id'], unique=False)

    op.create_table('contador_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proximo_numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('is_cnpj', sa.Boolean(), nullable=False),
    sa.Column('documento', sa.String(length=14), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=50), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=50), nullable=True),
    sa.Column('regime_tributario', sa.String(length=50), nullable=True),
    sa.Column('cnae_principal', sa.String(length=50), nullable=True),
    sa.Column('segmento', sa.String(length=50), nullable=True),
    sa.Column('indicador_ie', sa.String(length=1), nullable=True),
    sa.Column('natureza_juridica', sa.String(length=50), nullable=True),
    sa.Column('tipo_atividade', sa.String(length=20), nullable=True),
    sa.Column('cnaes_secundarios', sa.String(length=500), nullable=True),
    sa.Column('data_abertura', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('url_logo', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_empresas_id'), ['id'], unique=False)

    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_entidade', sa.Integer(), nullable=False),
    sa.Column('tipo_entidade', sa.Enum('CLIENTE', 'FORNECEDOR', 'FUNCIONARIO', 'EMPRESA', name='entitytype'), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Enum('ACRE', 'ALAGOAS', 'AMAPA', 'AMAZONAS', 'BAHIA', 'CEARA', 'DISTRITO_FEDERAL', 'ESPIRITO_SANTO', 'GOIAS', 'MARANHAO', 'MATO_GROSSO', 'MATO_GROSSO_DO_SUL', 'MINAS_GERAIS', 'PARA', 'PARAIBA', 'PARANA', 'PERNAMBUCO', 'PIAUI', 'RIO_DE_JANEIRO', 'RIO_GRANDE_DO_NORTE', 'RIO_GRANDE_DO_SUL', 'RONDONIA', 'RORAIMA', 'SANTA_CATARINA', 'SAO_PAULO', 'SERGIPE', 'TOCANTINS', name='state'), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.create_index('idx_entidade_tipo', ['id_entidade', 'tipo_entidade'], unique=False)

    op.create_table('formas_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('formas_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formas_pagamento_id'), ['id'], unique=False)

    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('ie', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('representante', sa.String(length=255), nullable=True),
    sa.Column('veiculo', sa.String(length=100), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('tipo_conta', sa.Enum('POUPANCA', 'CORRENTE', name='bankaccounttype'), nullable=True),
    sa.Column('pix', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('ie')
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_fornecedores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedores_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedores_nome_fantasia'), ['nome_fantasia'], unique=False)

    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicos_descricao'), ['descricao'], unique=False)
        batch_op.create_index(batch_op.f('ix_servicos_id'), ['id'], unique=False)

    op.create_table('terminais_conectados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hwid', sa.String(length=255), nullable=False),
    sa.Column('ultima_sinc', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terminais_conectados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terminais_conectados_hwid'), ['hwid'], unique=True)
        batch_op.create_index(batch_op.f('ix_terminais_conectados_id'), ['id'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('exp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('permissoes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_pf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMININO', 'OUTRO', name='gender'), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rg')
    )
    with op.batch_alter_table('clientes_pf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_pf_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_pf_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_pf_nome'), ['nome'], unique=False)

    op.create_table('clientes_pj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.Column('ie', sa.String(length=14), nullable=True),
    sa.Column('im', sa.String(length=14), nullable=True),
    sa.Column('regime_tributario', sa.String(length=20), nullable=True),
    sa.Column('responsavel', sa.String(length=255, collation='NOCASE'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ie'),
    sa.UniqueConstraint('im')
    )
    with op.batch_alter_table('clientes_pj', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_pj_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_pj_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_pj_nome_fantasia'), ['nome_fantasia'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_pj_razao_social'), ['razao_social'], unique=False)

    op.create_table('configuracoes_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('exigir_cpf_pf', sa.Boolean(), nullable=False),
    sa.Column('exigir_cnpj_pj', sa.Boolean(), nullable=False),
    sa.Column('exigir_celular', sa.Boolean(), nullable=False),
    sa.Column('exigir_rg_pf', sa.Boolean(), nullable=False),
    sa.Column('exigir_ie_pj', sa.Boolean(), nullable=False),
    sa.Column('exigir_email', sa.Boolean(), nullable=False),
    sa.Column('exigir_endereco', sa.Boolean(), nullable=False),
    sa.Column('tipo_pessoa_padrao', sa.String(length=2), nullable=False),
    sa.Column('exibir_genero', sa.Boolean(), nullable=False),
    sa.Column('exibir_data_nascimento', sa.Boolean(), nullable=False),
    sa.Column('bloquear_faturamento_inativo', sa.Boolean(), nullable=False),
    sa.Column('oferecer_reativacao_rapida', sa.Boolean(), nullable=False),
    sa.Column('ativar_limite_credito', sa.Boolean(), nullable=False),
    sa.Column('bloquear_venda_limite', sa.Boolean(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('configuracoes_clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_clientes_id'), ['id'], unique=False)

    op.create_table('configuracoes_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('prazo_entrega_padrao', sa.Integer(), nullable=False),
    sa.Column('garantia_padrao', sa.String(length=20), nullable=False),
    sa.Column('prazo_abandono_dias', sa.Integer(), nullable=False),
    sa.Column('taxa_diagnostico_padrao', sa.Integer(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('configuracoes_os', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_os_id'), ['id'], unique=False)

    op.create_table('configuracoes_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('exigir_codigo_barras', sa.Boolean(), nullable=False),
    sa.Column('exigir_categoria', sa.Boolean(), nullable=False),
    sa.Column('exigir_preco_custo', sa.Boolean(), nullable=False),
    sa.Column('margem_lucro_padrao', sa.Float(), nullable=False),
    sa.Column('utilizar_preco_atacado', sa.Boolean(), nullable=False),
    sa.Column('permitir_venda_estoque_zerado', sa.Boolean(), nullable=False),
    sa.Column('quantidade_minima_padrao', sa.Integer(), nullable=False),
    sa.Column('unidade_medida_padrao', sa.String(length=10), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('configuracoes_produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_produtos_id'), ['id'], unique=False)

    op.create_table('configuracoes_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('pin_gerente', sa.String(length=255), nullable=True),
    sa.Column('secoes_protegidas', sa.JSON(), nullable=False),
    sa.Column('requer_pin_cancelar_venda', sa.Boolean(), nullable=False),
    sa.Column('requer_pin_reabrir_venda', sa.Boolean(), nullable=False),
    sa.Column('requer_pin_desconto_venda', sa.Boolean(), nullable=False),
    sa.Column('requer_pin_alterar_preco_venda', sa.Boolean(), nullable=False),
    sa.Column('requer_pin_cancelar_os', sa.Boolean(), nullable=False),
    sa.Column('requer_pin_reabrir_os', sa.Boolean(), nullable=False),
    sa.Column('requer_pin_desconto_os', sa.Boolean(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('configuracoes_seguranca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_seguranca_id'), ['id'], unique=False)

    op.create_table('configuracoes_vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('permitir_desconto', sa.Boolean(), nullable=False),
    sa.Column('desconto_maximo_percent', sa.Integer(), nullable=False),
    sa.Column('exigir_cliente_identificado', sa.Boolean(), nullable=False),
    sa.Column('valor_minimo_venda', sa.Integer(), nullable=False),
    sa.Column('permitir_parcelamento', sa.Boolean(), nullable=False),
    sa.Column('parcelas_maximas', sa.Integer(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('configuracoes_vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_vendas_id'), ['id'], unique=False)

    op.create_table('empresa_fiscal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ambiente_emissao', sa.Integer(), nullable=False),
    sa.Column('serie_nfe', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_nfe', sa.Integer(), nullable=False),
    sa.Column('serie_nfce', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_nfce', sa.Integer(), nullable=False),
    sa.Column('csc_token', sa.String(length=100), nullable=True),
    sa.Column('csc_id', sa.String(length=10), nullable=True),
    sa.Column('rps_serie', sa.String(length=10), nullable=True),
    sa.Column('rps_ultimo_numero', sa.Integer(), nullable=False),
    sa.Column('prefeitura_login', sa.String(length=50), nullable=True),
    sa.Column('prefeitura_senha', sa.String(length=100), nullable=True),
    sa.Column('prefeitura_token_api', sa.String(length=200), nullable=True),
    sa.Column('regime_tributacao_iss', sa.Integer(), nullable=True),
    sa.Column('tipo_certificado', sa.String(length=10), nullable=False),
    sa.Column('certificado_digital_path', sa.String(length=500), nullable=True),
    sa.Column('certificado_validade', sa.DateTime(), nullable=True),
    sa.Column('certificado_subject', sa.String(length=300), nullable=True),
    sa.Column('certificado_thumbprint', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('empresa_fiscal_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_fiscal_settings_id'), ['id'], unique=False)

    op.create_table('ordem_servico_equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_equipamento', sa.Enum('COMPUTADOR', 'CELULAR', 'TABLET', 'IMPRESSORA', 'MONITOR', 'PRINTER', 'SCANNER', 'OUTROS', name='tipoequipamento'), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('imei', sa.String(length=20), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordem_servico_equipamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordem_servico_equipamentos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_servico_equipamentos_id'), ['id'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo_produto', sa.String(length=100), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('unidade_medida', sa.String(length=25), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(NOT ativo) OR (codigo_produto IS NOT NULL)', name='ck_codigo_produto_ativo_obrigatorio'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index('ix_produto_codigo_unico_ativo', ['codigo_produto'], unique=True, sqlite_where=sa.text('ativo IS 1'))
        batch_op.create_index(batch_op.f('ix_produtos_codigo_barras'), ['codigo_barras'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_codigo_produto'), ['codigo_produto'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('url_perfil', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade_ideal', sa.Integer(), nullable=True),
    sa.Column('quantidade_minima', sa.Integer(), nullable=True),
    sa.Column('valor_entrada', sa.Integer(), nullable=True),
    sa.Column('valor_varejo', sa.Integer(), nullable=False),
    sa.Column('valor_atacado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoque_id'), ['id'], unique=False)

    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('carteira_trabalho', sa.String(length=50), nullable=True),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMININO', 'OUTRO', name='gender'), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('titular_conta', sa.String(length=255), nullable=True),
    sa.Column('agencia', sa.String(length=10), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('banco', sa.String(length=50), nullable=True),
    sa.Column('tipo_conta', sa.Enum('POUPANCA', 'CORRENTE', name='bankaccounttype'), nullable=True),
    sa.Column('jornada_trabalho', sa.String(length=50), nullable=True),
    sa.Column('salario_bruto', sa.Integer(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('mae', sa.String(length=255), nullable=True),
    sa.Column('pai', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carteira_trabalho'),
    sa.UniqueConstraint('cnh'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('rg'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_id'), ['id'], unique=False)

    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', 'EDICAO_DADOS', name='movimentacaotipo'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade_anterior', sa.Integer(), nullable=False),
    sa.Column('quantidade_posterior', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_produto_id'), ['produto_id'], unique=False)

    op.create_table('produto_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto_fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_fotos_id'), ['id'], unique=False)

    op.create_table('comunicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_autor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_autor_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comunicados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunicados_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comunicados_id'), ['id'], unique=False)

    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_os', sa.String(length=20), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'AGUARDANDO_PECAS', 'AGUARDANDO_APROVACAO', 'AGUARDANDO_RETIRADA', 'FINALIZADA', 'CANCELADA', name='ordemservicostatus'), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'NORMAL', 'ALTA', 'URGENTE', name='ordemservicoprioridade'), nullable=False),
    sa.Column('defeito_relatado', sa.Text(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('situacao_equipamento', sa.Enum('REPARADO', 'SEM_REPARO', 'CONDENADO', name='situacaoequipamento'), nullable=True),
    sa.Column('senha_aparelho', sa.String(length=100), nullable=True),
    sa.Column('acessorios', sa.Text(), nullable=True),
    sa.Column('condicoes_aparelho', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('valor_total', sa.Integer(), nullable=False),
    sa.Column('valor_bruto', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Integer(), nullable=False),
    sa.Column('valor_entrada', sa.Integer(), nullable=False),
    sa.Column('taxa_entrega', sa.Integer(), nullable=False),
    sa.Column('acrescimo', sa.Integer(), nullable=False),
    sa.Column('credito_anterior', sa.Integer(), nullable=True),
    sa.Column('garantia', sa.String(length=20), nullable=True),
    sa.Column('data_previsao', sa.DateTime(), nullable=True),
    sa.Column('data_finalizacao', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['ordem_servico_equipamentos.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_servico_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_servico_numero_os'), ['numero_os'], unique=True)

    op.create_table('sessao_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='sessaocaixastatus'), nullable=False),
    sa.Column('saldo_inicial', sa.Integer(), nullable=False),
    sa.Column('saldo_final_esperado', sa.Integer(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.CheckConstraint('saldo_inicial >= 0', name='ck_sessao_caixa_saldo_inicial_nao_negativo'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessao_caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_caixa_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessao_caixa_id'), ['id'], unique=False)

    op.create_table('comunicados_leituras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comunicado_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('lido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comunicado_id'], ['comunicados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comunicado_id', 'funcionario_id')
    )
    with op.batch_alter_table('comunicados_leituras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comunicados_leituras_id'), ['id'], unique=False)

    op.create_table('ordem_servico_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordem_servico_fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordem_servico_fotos_id'), ['id'], unique=False)

    op.create_table('ordem_servico_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('PRODUTO', 'SERVICO', name='ordemservicoitemtipo'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.Enum('UNIDADE', 'KILO', 'GRAMA', 'LITRO', 'MILILITRO', 'METRO', 'CENTIMETRO', 'METRO_QUADRADO', 'METRO_CUBICO', 'HORA', 'DIA', 'MES', 'OUTROS', name='unidademedida'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Integer(), nullable=False),
    sa.CheckConstraint('NOT (produto_id IS NOT NULL AND servico_id IS NOT NULL)', name='ck_os_item_referencia_unica'),
    sa.CheckConstraint('quantidade > 0', name='ck_os_item_quantidade_positiva'),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordem_servico_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordem_servico_itens_id'), ['id'], unique=False)

    op.create_table('ordem_servico_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('bandeira_cartao', sa.String(length=50), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.CheckConstraint('parcelas >= 1', name='ck_os_pagamento_parcelas_min_1'),
    sa.CheckConstraint('valor >= 0', name='ck_os_pagamento_valor_nao_negativo'),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordem_servico_pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordem_servico_pagamentos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_servico_pagamentos_ordem_servico_id'), ['ordem_servico_id'], unique=False)

    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('sessao_caixa_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'FINALIZADA', 'CANCELADA', name='vendastatus'), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('observacao_interna', sa.String(length=500), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=500), nullable=True),
    sa.Column('numero_venda', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('entrega', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('entrega >= 0', name='ck_venda_entrega_nao_negativo'),
    sa.CheckConstraint('subtotal >= 0', name='ck_venda_subtotal_nao_negativo'),
    sa.CheckConstraint('total >= 0', name='ck_venda_total_nao_negativo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['sessao_caixa_id'], ['sessao_caixa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_venda')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_id'), ['id'], unique=False)

    op.create_table('logs_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_transacao', sa.Enum('ENTRADA', 'SAIDA_VENDA', 'ESTORNO', name='tipotransacaoestoque'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(tipo_transacao == 'ENTRADA') OR (venda_id IS NOT NULL)", name='ck_log_produto_tipo_transacao_valida'),
    sa.CheckConstraint('quantidade != 0', name='ck_log_produto_quantidade_nao_zero'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_produto_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_produto_produto_id'), ['produto_id'], unique=False)

    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('convertido', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('entrega', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('entrega >= 0', name='ck_orcamento_entrega_nao_negativo'),
    sa.CheckConstraint('subtotal >= 0', name='ck_orcamento_subtotal_nao_negativo'),
    sa.CheckConstraint('total >= 0', name='ck_orcamento_total_nao_negativo'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamentos_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamentos_id'), ['id'], unique=False)

    op.create_table('pagamentos_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('parcelado', sa.Boolean(), nullable=True),
    sa.Column('qtd_parcelas', sa.Integer(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(parcelado IS FALSE) AND (qtd_parcelas >= 1)', name='ck_pagamento_venda_parcelas_min_1'),
    sa.CheckConstraint('valor > 0', name='ck_pagamento_venda_valor_positivo'),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_venda_id'), ['venda_id'], unique=False)

    op.create_table('produtos_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_produto', sa.Enum('CADASTRADO', 'AVULSO', name='tipoprodutovenda'), nullable=False),
    sa.Column('descricao_avulsa', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.CheckConstraint("((tipo_produto = 'CADASTRADO') AND (produto_id IS NOT NULL)) OR ((tipo_produto = 'AVULSO') AND (descricao_avulsa IS NOT NULL) AND (produto_id IS NULL))", name='ck_produto_venda_tipo_referencia_consistente'),
    sa.CheckConstraint('(produto_id IS NOT NULL) OR (descricao_avulsa IS NOT NULL)', name='ck_produto_venda_referencia_obrigatoria'),
    sa.CheckConstraint('desconto >= 0', name='ck_produto_venda_desconto_nao_negativo'),
    sa.CheckConstraint('quantidade > 0', name='ck_produto_venda_qtd_positiva'),
    sa.CheckConstraint('valor_unitario >= 0', name='ck_produto_venda_valor_unitario_nao_negativo'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_venda_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_venda_venda_id'), ['venda_id'], unique=False)

    op.create_table('orcamentos_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_produto', sa.Enum('CADASTRADO', 'AVULSO', name='tipoprodutovenda'), nullable=False),
    sa.Column('descricao_avulsa', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.CheckConstraint("((tipo_produto = 'CADASTRADO') AND (produto_id IS NOT NULL)) OR ((tipo_produto = 'AVULSO') AND (descricao_avulsa IS NOT NULL) AND (produto_id IS NULL))", name='ck_orcamento_produto_tipo_referencia_consistente'),
    sa.CheckConstraint('(produto_id IS NOT NULL) OR (descricao_avulsa IS NOT NULL)', name='ck_orcamento_produto_referencia_obrigatoria'),
    sa.CheckConstraint('desconto >= 0', name='ck_orcamento_produto_desconto_nao_negativo'),
    sa.CheckConstraint('quantidade > 0', name='ck_orcamento_produto_qtd_positiva'),
    sa.CheckConstraint('valor_unitario >= 0', name='ck_orcamento_produto_valor_unitario_nao_negativo'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamentos_produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamentos_produtos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamentos_produtos_orcamento_id'), ['orcamento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamentos_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_produtos_orcamento_id'))
        batch_op.drop_index(batch_op.f('ix_orcamentos_produtos_id'))

    op.drop_table('orcamentos_produtos')
    with op.batch_alter_table('produtos_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_venda_venda_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_venda_id'))

    op.drop_table('produtos_venda')
    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_venda_id'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_id'))

    op.drop_table('pagamentos_venda')
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_id'))
        batch_op.drop_index(batch_op.f('ix_orcamentos_funcionario_id'))

    op.drop_table('orcamentos')
    with op.batch_alter_table('logs_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_produto_produto_id'))
        batch_op.drop_index(batch_op.f('ix_logs_produto_id'))

    op.drop_table('logs_produto')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_id'))
        batch_op.drop_index(batch_op.f('ix_vendas_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_vendas_cliente_id'))

    op.drop_table('vendas')
    with op.batch_alter_table('ordem_servico_pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordem_servico_pagamentos_ordem_servico_id'))
        batch_op.drop_index(batch_op.f('ix_ordem_servico_pagamentos_id'))

    op.drop_table('ordem_servico_pagamentos')
    with op.batch_alter_table('ordem_servico_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordem_servico_itens_id'))

    op.drop_table('ordem_servico_itens')
    with op.batch_alter_table('ordem_servico_fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordem_servico_fotos_id'))

    op.drop_table('ordem_servico_fotos')
    with op.batch_alter_table('comunicados_leituras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunicados_leituras_id'))

    op.drop_table('comunicados_leituras')
    with op.batch_alter_table('sessao_caixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_caixa_id'))
        batch_op.drop_index(batch_op.f('ix_sessao_caixa_funcionario_id'))

    op.drop_table('sessao_caixa')
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_servico_numero_os'))
        batch_op.drop_index(batch_op.f('ix_ordens_servico_id'))

    op.drop_table('ordens_servico')
    with op.batch_alter_table('comunicados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comunicados_id'))
        batch_op.drop_index(batch_op.f('ix_comunicados_empresa_id'))

    op.drop_table('comunicados')
    with op.batch_alter_table('produto_fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_fotos_id'))

    op.drop_table('produto_fotos')
    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_id'))

    op.drop_table('movimentacoes_estoque')
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_id'))

    op.drop_table('funcionarios')
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_id'))

    op.drop_table('estoque')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_codigo_produto'))
        batch_op.drop_index(batch_op.f('ix_produtos_codigo_barras'))
        batch_op.drop_index('ix_produto_codigo_unico_ativo', sqlite_where=sa.text('ativo IS 1'))

    op.drop_table('produtos')
    with op.batch_alter_table('ordem_servico_equipamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordem_servico_equipamentos_id'))
        batch_op.drop_index(batch_op.f('ix_ordem_servico_equipamentos_cliente_id'))

    op.drop_table('ordem_servico_equipamentos')
    with op.batch_alter_table('empresa_fiscal_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_fiscal_settings_id'))

    op.drop_table('empresa_fiscal_settings')
    with op.batch_alter_table('configuracoes_vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_vendas_id'))

    op.drop_table('configuracoes_vendas')
    with op.batch_alter_table('configuracoes_seguranca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_seguranca_id'))

    op.drop_table('configuracoes_seguranca')
    with op.batch_alter_table('configuracoes_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_produtos_id'))

    op.drop_table('configuracoes_produtos')
    with op.batch_alter_table('configuracoes_os', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_os_id'))

    op.drop_table('configuracoes_os')
    with op.batch_alter_table('configuracoes_clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_clientes_id'))

    op.drop_table('configuracoes_clientes')
    with op.batch_alter_table('clientes_pj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_pj_razao_social'))
        batch_op.drop_index(batch_op.f('ix_clientes_pj_nome_fantasia'))
        batch_op.drop_index(batch_op.f('ix_clientes_pj_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_pj_cnpj'))

    op.drop_table('clientes_pj')
    with op.batch_alter_table('clientes_pf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_pf_nome'))
        batch_op.drop_index(batch_op.f('ix_clientes_pf_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_pf_cpf'))

    op.drop_table('clientes_pf')
    op.drop_table('cargos')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('terminais_conectados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminais_conectados_id'))
        batch_op.drop_index(batch_op.f('ix_terminais_conectados_hwid'))

    op.drop_table('terminais_conectados')
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicos_id'))
        batch_op.drop_index(batch_op.f('ix_servicos_descricao'))

    op.drop_table('servicos')
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_nome_fantasia'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_nome'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_id'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_cnpj'))

    op.drop_table('fornecedores')
    with op.batch_alter_table('formas_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formas_pagamento_id'))

    op.drop_table('formas_pagamento')
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_index('idx_entidade_tipo')

    op.drop_table('enderecos')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_id'))
        batch_op.drop_index(batch_op.f('ix_empresas_documento'))

    op.drop_table('empresas')
    op.drop_table('contador_venda')
    with op.batch_alter_table('configuracoes_licenca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_licenca_id'))
        batch_op.drop_index(batch_op.f('ix_configuracoes_licenca_hwid'))

    op.drop_table('configuracoes_licenca')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_id'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
